# Generated by Django 3.2.5 on 2021-09-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user_name',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('order cancled', 'order canceled '), ('order is on the way', 'order is on the way '), ('order processing', 'order processing '), ('order received', 'order received '), ('order completed', 'order completed ')], max_length=200),
        ),
    ]
