# Generated by Django 3.2.5 on 2021-09-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210929_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('order completed', 'order completed '), ('order cancled', 'order canceled '), ('order processing', 'order processing '), ('order received', 'order received '), ('order is on the way', 'order is on the way ')], max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='pyment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery '), ('Card Payment', 'Card Payment ')], default='Cash on Delivery', max_length=30),
        ),
    ]
