# Generated by Django 3.2.5 on 2021-10-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20210930_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('order cancled', 'order canceled '), ('order received', 'order received '), ('order is on the way', 'order is on the way '), ('order processing', 'order processing '), ('order completed', 'order completed ')], max_length=200),
        ),
    ]
