# Generated by Django 3.2.8 on 2021-10-19 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20211014_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('order completed', 'order completed '), ('order is on the way', 'order is on the way '), ('order processing', 'order processing '), ('order cancled', 'order canceled '), ('order received', 'order received ')], max_length=200),
        ),
        migrations.CreateModel(
            name='Pimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ima', models.ImageField(upload_to='product/images')),
                ('proimage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.product')),
            ],
        ),
    ]
