# Generated by Django 3.2.8 on 2021-11-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20211019_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('order cancled', 'order canceled '), ('order processing', 'order processing '), ('order received', 'order received '), ('order is on the way', 'order is on the way '), ('order completed', 'order completed ')], max_length=200),
        ),
    ]
