# Generated by Django 3.2.8 on 2021-12-30 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0007_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('order completed', 'order completed '), ('order is on the way', 'order is on the way '), ('order received', 'order received '), ('order cancled', 'order canceled '), ('order processing', 'order processing ')], max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='pyment_method',
            field=models.CharField(choices=[('Card Payment', 'Card Payment '), ('Cash on Delivery', 'Cash on Delivery ')], default='Cash on Delivery', max_length=30),
        ),
    ]
